#配置端口号
server:
  port: 8081
spring:
  application:
    name: family-edu
  datasource:
    url: jdbc:mysql://localhost:3306/db_edu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.senb.familyedu: debug